#!/bin/bash

# Loads X applications configuration
/usr/bin/xrdb -merge ~/.Xresources

# Starts gnome-keyring-daemon and exports its variables
eval $(/usr/bin/gnome-keyring-daemon --start)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

# Starts urxvtd daemon
/usr/bin/urxvtd -o -f -q

# Starts other components in the background
/usr/bin/xcompmgr -cF &
/usr/bin/gnome-sound-applet &
/usr/bin/parcellite &
/usr/bin/dropboxd &
/usr/bin/xscreensaver -no-splash &
/usr/bin/nm-applet &

# Starts polkit server
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Starts polkit dependant services
/usr/bin/nm-applet &

exec /usr/bin/awesome
