#!/bin/sh

export LANG=fr_FR.UTF-8

# Configures screen on identified hostname
case $(hostname) in
	thor) /usr/local/bin/screen-config;;
esac


# Disables speaker
xset -b

# Loads X applications configuration
xrdb -load ~/.Xresources
setxkbmap fr bepo

if [ "$SESSION" == "gnome" ]; then
	exec gnome-session
else
	# Starts gnome-keyring-daemon and exports its variables
	# eval $(gnome-keyring-daemon --start --components=secrets )
	# Starts ssh agent and exports its variables
	eval $(ssh-agent)

	# Starts pulseaudio
	if [ $(which pulseaudio) != "" ]; then
	    pulseaudio --start
	fi

	# Starts other components in the background
	compton -b
	parcellite &
	if [ $(which dropbox) != "" ]; then
	    dropbox &
	fi
	xautolock -detectsleep -time 10 -locker "$HOME/.config/awesome/bin/xlock" &

	# Starts polkit server
	#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

	# Starts polkit dependant services
	nm-applet &

	# Starts autossh tunnel to honir
	#if [ -f ~/.ssh/config ]; then
	#	if grep -q 'Host honir-tunnel$' ~/.ssh/config; then
	#		/usr/bin/autossh -xaNf -M 20000 honir-tunnel
	#	fi
	#	if [ -d ~/.config/lsync ] && grep -q 'Host honir$' ~/.ssh/config; then
	#		/usr/bin/lsyncd ~/.config/lsync/etc/lsyncd-client.conf
	#		~/.config/lsync/bin/lsync &
	#	fi
	#fi

	exec awesome
fi
